on:
  issues: 
    types: [labeled, unlabeled]
    
jobs:
  security-check:
    runs-on: ubuntu-latest
    #if: github.event.label.name == 'security-check'

    env:
      body: ${{ github.event.issue.body }}

    steps:
    - uses: actions/checkout@v2
    
    - run: |
         echo 'Found the issue that triggered this event with number [${{ github.event.issue.number }}]'
         echo 'Found the issue title [${{ github.event.issue.title }}]'
         echo -e $body

    - uses: actions/github-script@v5
      with:
        script: |
            console.log(context.issue.number)
            console.log(context.repo.owner)
            console.log(context.repo.repo)

            // todo, figure out pagination:
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })

            console.log(comments)

            if (comments.length > 0) {
              // find latest
              console.log("a")
              let lastItem = comments[comments.length-1]
            } else {
              console.log("b")
              let lastItem = comments
            }


            console.log("c")
            console.log(lastItem)
