on:
  issues: 
    types: [labeled]
    
jobs:
  security-check:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'security-check'

    env:
      body: ${{ github.event.issue.body }}

    steps:
    - uses: actions/checkout@v2
    
    - run: |
         echo 'Found the issue that triggered this event with number [${{ github.event.issue.number }}]'
         echo 'Found the issue title [${{ github.event.issue.title }}]'
         echo -e $body

    - uses: actions/github-script@v5
      with:
        script: |
            const options = github.rest.issues.getComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })

            const comments = await github.paginate(options)

            for (const comment of comments) {
              console.log(comment.body)
            }