on:
  issues: 
    types: [labeled, unlabeled]
    
jobs:
  security-check:
    runs-on: ubuntu-latest
    #if: github.event.label.name == 'security-check'

    env:
      body: ${{ github.event.issue.body }}

    steps:
    - run: |
         echo 'Found the issue that triggered this event with number [${{ github.event.issue.number }}]'
         echo 'Found the issue title [${{ github.event.issue.title }}]'
         echo -e $body

    - uses: actions/github-script@v5
      name: Find action from comment
      id: get-action
      with:
        result-encoding: string
        script: |
            // todo, figure out pagination:

            const owner = context.repo.owner
            const repo = context.repo.repo
            const issue_number = context.issue.number

            // load all comments for this issue
            const comments = await github.rest.issues.listComments({
              owner: owner,
              repo: repo,
              issue_number: issue_number,
            })

            // find the last comment
            let lastItem
            if (comments.data.length > 1) {
              // find latest
              lastItem = comments.data[comments.data.length-1]
            } else {
              lastItem = comments.data
            }

            const body = lastItem.body
            console.log(body)

            let action
            if (!body.startsWith('uses: ')) {              
              console.log('no action found')

              let body = [
                "Couldn't find the action uses statement in the last comment.",
                "Please create a comment that only has `uses: owner/action-name` in it.",
                "",
                ":robot:"
              ]
              
              // create comment letting the user now what to do
              github.rest.issues.createComment({
                owner,
                repo,
                issue_number,
                body: body.join('\n')
              });

              return
            } 

            // todo: search for last space as well to cut off the name at the end for more flexibility
            action = body.substring(6)
            console.log(`Found action with name ${action}`)
            console.log(action)

            // return action
            let index = action.indexOf('/')
            let actionOwner = action.substring(0, index)
            let actionName = action.substring(index+1)

            console.log(`Found owner:${actionOwner}`)
            console.log(`Found action:${actionName}`)

            console.log(`::set-output name=action::${action}`)
            console.log(`::set-output name=owner::${actionOwner}`)
            console.log(`::set-output name=name::${actionName}`)
      
            console.log(`::set-output name=request_owner::${owner}`)            
            console.log(`::set-output name=request_repo::${repo}`)
            console.log(`::set-output name=request_issue::${issue_number}`)
    
    - name: Check-out referenced Action
      run: |
        git clone https://github.com/${{ steps.get-action.outputs.action }} action

    - name: Check Dependabot configuration
      id: has-dependabot-configuration
      run: |
        echo "Looking for 'dependabot.yml' in '.github' folder of the action"
        if [ -d "action/.github" ] && [ -n (find .github -maxdepth 1 -name dependabot.yml) ] ; then
          jq -nc '{"body": "✅ Dependabot configuration found"}' | \
          curl -sL  -X POST -d @- \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ steps.get-action.outputs.request_owner }}/${{ steps.get-action.outputs.request_repo }}/issues/${{ steps.get-action.outputs.request_issue }}/comments"
        else
          jq -nc '{"body": "⛔️ No Dependabot configuration found"}' | \
          curl -sL  -X POST -d @- \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ steps.get-action.outputs.request_owner }}/${{ steps.get-action.outputs.request_repo }}/issues/${{ steps.get-action.outputs.request_issue }}/comments"
        fi

    - name: Check CodeQL step in Workflow
      id: has-codeql-in-workflow
      run: |
        echo "Looking for CodeQL action in any Workflow of the action"
        if [ ! -d "action/.github/workflows" ]; then
          jq -nc '{"body": "⛔️ No workflows found"}' | \
            curl -sL  -X POST -d @- \
              -H "Content-Type: application/json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ steps.get-action.outputs.request_owner }}/${{ steps.get-action.outputs.request_repo }}/issues/${{ steps.get-action.outputs.request_issue }}/comments"
        else
          if [ `grep action/.github/workflows/*.yml -e 'uses: github/codeql-action/init' | wc -l` -gt 0 ]; then
            WORKFLOW=`grep action/.github/workflows/*.yml -e 'uses: github/codeql-action/init' -H | cut -f1 -d' ' | sed "s/:$//g"`
            jq -nc "{\"body\": \"✅ CodeQL Init step found in $WORKFLOW\"}" | \
            curl -sL  -X POST -d @- \
              -H "Content-Type: application/json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ steps.get-action.outputs.request_owner }}/${{ steps.get-action.outputs.request_repo }}/issues/${{ steps.get-action.outputs.request_issue }}/comments"
          else
            jq -nc '{"body": "⛔️ No CodeQL Init step found"}' | \
            curl -sL  -X POST -d @- \
              -H "Content-Type: application/json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ steps.get-action.outputs.request_owner }}/${{ steps.get-action.outputs.request_repo }}/issues/${{ steps.get-action.outputs.request_issue }}/comments"
          fi

          if [ `grep action/.github/workflows/*.yml -e 'uses: github/codeql-action/analyze' | wc -l` -gt 0 ]; then
            WORKFLOW=`grep action/.github/workflows/*.yml -e 'uses: github/codeql-action/analyze' -H | cut -f1 -d' ' | sed "s/:$//g"`
            jq -nc "{\"body\": \"✅ CodeQL Analyze step found in $WORKFLOW\"}" | \
            curl -sL  -X POST -d @- \
              -H "Content-Type: application/json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ steps.get-action.outputs.request_owner }}/${{ steps.get-action.outputs.request_repo }}/issues/${{ steps.get-action.outputs.request_issue }}/comments"
          else
            jq -nc '{"body": "⛔️ No CodeQL Analyze step found"}' | \
            curl -sL  -X POST -d @- \
              -H "Content-Type: application/json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ steps.get-action.outputs.request_owner }}/${{ steps.get-action.outputs.request_repo }}/issues/${{ steps.get-action.outputs.request_issue }}/comments"
          fi
        fi
    
    - name: Scan docker container when present
      id: scan-docker-container-when-present
      run: |
        #!/bin/bash

        set -ueo pipefail

        if [ "docker" != `yq e '.runs.using' action/action.yml` ] ; then
          jq -nc '{"body": "Action is not using a Docker image"}' | \
          curl -sL  -X POST -d @- \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ steps.get-action.outputs.request_owner }}/${{ steps.get-action.outputs.request_repo }}/issues/${{ steps.get-action.outputs.request_issue }}/comments"
                    
          exit 0
        fi

        echo "Installing trivy"
        sudo apt-get install wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy

        if [ "Dockerfile" == `yq e '.runs.image' action/action.yml` ]; then
          echo "Scan docker image with trivy"
          docker build -t action-checkout/${{ steps.get-action.outputs.action }} action/
          trivy --quiet image action-checkout/${{ steps.get-action.outputs.action }} > issues
          docker image rm action-checkout/${{ steps.get-action.outputs.action }}
        else
          echo "Scan docker image with trivy"
          trivy --quiet image $IMAGE > issues
        fi

        # Check if LOW or MEDIUM issues are found
        if [ `cat issues | grep -e LOW -e MEDIUM | wc -l` -gt 1 ] ; then
          jq -nc '{"body": "⚠️ Docker image scanning found LOW or MEDIUM issues. Please check the logs."}' | \
            curl -sL  -X POST -d @- \
              -H "Content-Type: application/json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ steps.get-action.outputs.request_owner }}/${{ steps.get-action.outputs.request_repo }}/issues/${{ steps.get-action.outputs.request_issue }}/comments"
        fi

        # Check if HIGH or CRITICAL issues are found
        if [ `cat issues | grep -e HIGH -e CRITICAL | wc -l` -gt 1 ] ; then
          jq -nc '{"body": "⛔ Docker image scanning found HIGH or CRITICAL issues. Please check the logs."}' | \
            curl -sL  -X POST -d @- \
              -H "Content-Type: application/json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ steps.get-action.outputs.request_owner }}/${{ steps.get-action.outputs.request_repo }}/issues/${{ steps.get-action.outputs.request_issue }}/comments"
            
            exit 17
        fi

    - name: Get result for verification
      run: |
        echo "Owner: ${{steps.get-action.outputs.owner}}"
        echo "Name: ${{steps.get-action.outputs.name}}"

    # todo: add a new comment to the issue indication the action of forking the repo over to the other org?

    - name: Fork the action repository to rajbos-actions-test
      uses: rajbos-actions/forker@v0.0.1
      with:
        token: ${{ secrets.GH_TOKEN }}
        repo: ${{steps.get-action.outputs.name}}
        owner: ${{steps.get-action.outputs.owner}}
        org: rajbos-actions-test # todo: make central parameter

    # since dependabot alerts and dependency graph is enabled on the organization level, we only need to add a CodeQL setup
    # for it we need to inject the default CodeQL config into the forked action repository
    - uses: actions/github-script@v5
      name: Inject CodeQL workflow into new forked repository
      id: CodeQL
      env:
        repo: ${{steps.get-action.outputs.name}}
        org: rajbos-actions-test # todo: make central parameter
      with:      
        github-token: ${{ secrets.GH_TOKEN }}  
        script: |            
            const { repo, org } = process.env
            console.log(`Hello ${org}/${repo}`)

            const { readFileSync } = require('fs')
            const path = 'codeql-analysis.yml'
            const content = readFileSync(`${process.env.GITHUB_WORKSPACE}/${path}`)

            const targetPath = ".github/workflows/codeql-analysis.yml"
            const { data } = await github.rest.repos.getContent({ 
              owner: org,
              repo,
              path: ".github/workflows/codeql-analysis.yml" 
            })

            console.log('data:')
            console.log(data)
            
            console.log('data.content:')
            console.log(data.content)

            if (data === null) {
              console.log('data is null')
            }

            content2 = Buffer.from(content.toString('base64'), 'base64')
            console.log('content2')
            console.log(content2)

            if (Buffer.from(data.content, 'base64').compare(content2) === 0) {
              console.log('data in the codeql workflow file is the same. Halting execution')
              return
            }
                        
            // todo: test if file already exists
            github.rest.repos.createOrUpdateFileContents({
              owner: org,
              repo,
              path: targetPath,
              message: "Adding CodeQL setup",
              content: content2.toString('base64'),
              sha: data.sha
            })

            // todo: trigger the CodeQL workflow is default branch != main (hardcoded in the workflow file)
            // todo: generate random cron schedule?
