on:
  issues: 
    types: [labeled, unlabeled]
    
jobs:
  security-check:
    runs-on: ubuntu-latest
    #if: github.event.label.name == 'security-check'

    env:
      body: ${{ github.event.issue.body }}

    steps:
    - uses: actions/checkout@v2
    
    - run: |
         echo 'Found the issue that triggered this event with number [${{ github.event.issue.number }}]'
         echo 'Found the issue title [${{ github.event.issue.title }}]'
         echo -e $body

    - uses: actions/github-script@v5
      name: Find action from comment
      id: get-action
      with:
        result-encoding: string
        script: |
            // todo, figure out pagination:

            const owner = context.repo.owner
            const repo = context.repo.repo
            const issue_number = context.issue.number

            // load all comments for this issue
            const comments = await github.rest.issues.listComments({
              owner: owner,
              repo: repo,
              issue_number: issue_number,
            })

            // find the last comment
            let lastItem
            if (comments.data.length > 1) {
              // find latest
              lastItem = comments.data[comments.data.length-1]
            } else {
              lastItem = comments.data
            }

            const body = lastItem.body
            console.log(body)

            let action
            if (!body.startsWith('uses: ')) {              
              console.log('no action found')

              let body = [
                "Couldn't find the action uses statement in the last comment.",
                "Please create a comment that only has `uses: owner/action-name` in it.",
                "",
                ":robot:"
              ]
              
              // create comment letting the user now what to do
              github.rest.issues.createComment({
                owner,
                repo,
                issue_number,
                body: body.join('\n')
              });

              return
            } 

            // todo: search for last space as well to cut off the name at the end for more flexibility
            action = body.substring(6)
            console.log(`Found action with name ${action}`)
            console.log(action)

            // return action
            let index = action.indexOf('/')
            let owner = action.substring(0, index)
            let name = action.substring(index+1)
            console.log("::set-output name=owner::owner")
            console.log("::set-output name=name::name")

            return action

    - name: Get result
      run: |
        echo "Result: ${{steps.get-action.outputs.result}}"
        echo "Owner: ${{steps.get-action.outputs.owner}}"
        echo "Name: ${{steps.get-action.outputs.name}}"

    - name: Fork the action repository to rajbos-actions-test
      uses: rajbos-actions/forker@v0.0.1
      with:
        token: ${{ secrets.GH_TOKEN }}
        repo: rajbos-actions
        owner: forker
        org: rajbos-actions-test
