on:
  issues: 
    types: [labeled, unlabeled]
    
jobs:
  security-check:
    runs-on: ubuntu-latest
    #if: github.event.label.name == 'security-check'

    env:
      body: ${{ github.event.issue.body }}

    steps:
    - uses: actions/checkout@v2
    
    - run: |
         echo 'Found the issue that triggered this event with number [${{ github.event.issue.number }}]'
         echo 'Found the issue title [${{ github.event.issue.title }}]'
         echo -e $body

    - uses: actions/github-script@v5
      name: Find action from comment
      with:
        script: |
            // todo, figure out pagination:

            // load all comments for this issue
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })

            // find the last comment
            let lastItem
            if (comments.data.length > 1) {
              // find latest
              lastItem = comments.data[comments.data.length-1]
            } else {
              lastItem = comments.data
            }

            const body = lastItem.body
            console.log(body)

            let action
            if (!body.startsWith('uses: ')) {              
              console.log('nope')
              // todo: create comment letting the user now what to do
              return
            } 

            // todo: search for last space as well to cut off the name at the end for more flexibility
            action = body.substring(6)
            console.log(`Found action with name ${action}`)
            console.log(action)

            
