name: Handle new issue form
on:
 issues:
    types: [opened, labeled, unlabeled]

jobs:
  issue:
    runs-on: ubuntu-latest
    steps:   
    - uses: actions/checkout@v2 

    - uses: actions/github-script@v5
      name: Find action from body
      id: get-action
      with:
        result-encoding: string
        script: |
          const script = require('./src/find-action-from-comment.js')
                  
          const owner = context.repo.owner
          const repo = context.repo.repo
          const issue_number = context.issue.number
          
          console.log(await script({github, owner, repo, issue_number, core}))